version: '3.9'
services:
  anime-api:
    container_name: anime-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - mongodb-network
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: mongo-db #this is the name of the mongo container in the docker compose file
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_COLLECTION: ${DB_COLLECTION}
    depends_on:
      - mongo-db
    volumes:
      - .:/var/www/html/anime-api
      - /var/www/html/anime-api/node_modules

  mongo-db:
    image: mongo:7
    restart: always
    container_name: mongo-db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_COLLECTION: ${DB_COLLECTION}
    volumes:
      - data-mongo-dev:/data/db
      - ./src/Utils/db/api-init-db.js:/docker-entrypoint-initdb.d/api-db-init.js
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
    name: mongodb-network

volumes:
  data-mongo-dev:
